use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct RawPyProject {
    project: Option<ProjectTable>,
    #[serde(rename = "dependency-groups")]
    dependency_groups: Option<BTreeMap<String, Vec<String>>>,
    tool: Option<ToolTable>,
}

#[derive(Debug, Deserialize)]
struct ProjectTable {
    dependencies: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
struct ToolTable {
    uv: Option<UvToolTable>,
}

#[derive(Debug, Deserialize)]
struct UvToolTable {
    #[serde(rename = "dev-dependencies")]
    dev_dependencies: Option<Vec<String>>,
}

pub(crate) fn editable_install_target(extras: &[String]) -> String {
    if extras.is_empty() {
        return ".".to_string();
    }
    format!(".[{}]", extras.join(","))
}

pub(crate) fn ensure_readme(target: &Path) -> Result<()> {
    let readme = target.join("README.md");
    if !readme.exists() {
        eprintln!(
            "Generating basic readme at {} to satisfy pip",
            readme.display()
        );
        fs::write(readme, "# Basic readme generated by Plato")?;
    }
    Ok(())
}

pub(crate) fn get_or_create_requirements_file(target: &Path) -> Result<PathBuf> {
    let requirements = target.join("requirements.txt");
    if requirements.exists() {
        return Ok(requirements);
    }

    let pyproject = target.join("pyproject.toml");
    if !pyproject.exists() {
        bail!("Could not find requirements.txt or pyproject.toml for scope 'requirements'.");
    }

    let requirements = requirements_from_pyproject(&pyproject).with_context(|| {
        format!(
            "Unable to extract requirements from pyproject.toml at {}",
            pyproject.display()
        )
    })?;
    let hidden_path = target.join(".plato");
    fs::create_dir_all(&hidden_path).with_context(|| {
        format!(
            "Unable to create hidden path at {}/.plato/",
            target.display()
        )
    })?;
    let file_path = hidden_path.join("requirements.txt");
    fs::write(&file_path, requirements.join("\n")).with_context(|| {
        format!(
            "Unable to create requirements file at {}",
            file_path.display()
        )
    })?;
    Ok(file_path)
}

fn requirements_from_pyproject(path: &Path) -> Result<Vec<String>> {
    let raw = fs::read_to_string(path)
        .with_context(|| format!("Unable to read pyproject.toml at {}", path.display()))?;
    let pyproject: RawPyProject = toml::from_str(&raw)
        .with_context(|| format!("Unable to parse pyproject.toml at {}", path.display()))?;
    let mut requirements = Vec::new();
    if let Some(deps) = pyproject.project.and_then(|project| project.dependencies) {
        requirements.extend(deps);
    }
    if let Some(groups) = pyproject.dependency_groups {
        for deps in groups.into_values() {
            requirements.extend(deps);
        }
    }
    if let Some(dev_deps) = pyproject
        .tool
        .and_then(|tool| tool.uv)
        .and_then(|uv| uv.dev_dependencies)
    {
        requirements.extend(dev_deps);
    }
    Ok(requirements)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn editable_install_target_includes_extras() {
        assert_eq!(editable_install_target(&[]), ".");
        assert_eq!(editable_install_target(&["cli".to_string()]), ".[cli]");
    }
}
