[package]
name = "plato-plugin-pnpm"
version = "0.1.0"
description = "pnpm setup plugin for Plato"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "plato-plugin-pnpm"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
plato-plugin-api.workspace = true
plato-plugin-support.workspace = true
