[package]
name = "plto-plugin-cargo"
version = "1.0.0"
description = "Cargo setup plugin for Plato"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "plto-plugin-cargo"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
plto-plugin-api.workspace = true
plto-plugin-support.workspace = true
